import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function About() {

  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              rel="noopener noreferrer"
            >
              Home
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <h1>
            About
          </h1>
        </div>

        <div className={styles.grid}>
          <a
            href="/"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
              Home <span>-&gt;</span>
            </h2>
            <p>
              Ir a la pagina Home
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
