import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [count, setCount] = useState(0)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
          </div>
        </div>

        <div className={styles.center}>
          <h1>
            Amo a mis pechochos Viani<span>💖</span> , cuyolo🐱 y hironcio🐱 
          </h1>
        </div>

        <h3>
            Contador: {count}
          </h3>
        <div className={styles.grid}>
          <div
            className={styles.card}
            onClick={() => setCount(count + 1)}
          >
            <h2>
              Sumar
            </h2>
          </div>
        </div>
        <div className={styles.grid}>
          <div
            className={styles.card}
            onClick={() => setCount(count - 1)}
          >
            <h2>
              Restar
            </h2>
          </div>
          </div>
      </main>
    </>
  )
}
